title: Stephanie Boissonneault
logo: /assets/img/Framed%20Headshot.png
description: Data Analytics, Big Data, and Predictive Analytics Certificate Student
descritpion: text below image
show_downloads: true
theme: jekyll-theme-minimal

